name: Publish GrapesJS Components-Tabs rc
on:
  push:
    branches: [master]

jobs:
  publish:
    if: "contains(github.event.head_commit.message, 'Release GrapesJS Components Tabs rc:')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Build components-tabs
        run: npm run build
      - name: Check components-tabs TS
        run: npm run ts:check
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          npm run publish:rc
